case {os:getenv("XPROF_JSON_LIB"), erlang:function:exported(json, encode, 1)} of
    {false, false} ->
        CONFIG;
    _ ->
        %% Delete jsone from list of applications
        [{application, App, Opts}] = CONFIG,
        Apps = proplists:get_value(applications, Opts),
        NewOpts = lists:keystore(applications, 1, Opts, {applications, Apps -- [jsone]}),
        [{application, App, NewOpts}]
end.
